
profile="custom"
[msbuild]
project = "ResumeBuilder.sln"
[msbuild.properties]
PublishTrimmed = false
[github]
user = "leotsarev"
repo = "ResumeBuilder"
[brew]
publish=false
[scoop]
publish=false
[nuget]
publish=false
[[pack]]
rid = ["win-x64"]
kinds = ["zip"]
[[pack]]
rid = ["linux-x64"]
kinds = ["tar"]