profile="custom"
[msbuild]
project = "ResumeBuilder.sln"
[github]
user = "leotsarev"
repo = "ResumeBuilder"
[homebrew]
publish=false
[nuget]
publish=false
[[pack]]
rid = ["win-x64"]
kinds = ["zip"]
[[pack]]
rid = ["linux-x64"]
kinds = ["tar"]