using Markdig;
using Markdig.Extensions.Yaml;
using Markdig.Syntax;
using System.Net;

namespace Tsarev.ResumeBuilder;

internal class HtmlOutput(MarkdownPipeline markdownPipeline, MarkdownDocument document)
{
    private readonly ResumeFrontMatter frontMatterBlock =  document.Descendants<YamlFrontMatterBlock>().FirstOrDefault().GetFrontMatter();

    private string Title => WebUtility.HtmlEncode(frontMatterBlock.Title ?? "Резюме");
    private string Author => WebUtility.HtmlEncode(frontMatterBlock.Author ?? "Иванов Иван Иваныч");
    private string Description => WebUtility.HtmlEncode(frontMatterBlock.Title ?? "Резюме " + Author);
    private string Language => WebUtility.HtmlEncode(frontMatterBlock.Language ?? "ru");

    public string WriteHtml()
    {
        var result = Markdown.ToHtml(document, markdownPipeline);

        return $"""
            <!DOCTYPE html>
            <html lang="{Language}">
            {GetHead()}
            <body>
            {result}
            </body>
            </html>
            """.ReplaceLineEndings();
    }

    private string GetHead()
    {
        return $"""
                <head>
                  <meta http-equiv="X-UA-Compatible" content="IE=edge">
                  <meta http-equiv="content-type" content="text/html; charset=utf-8">

                  <!-- Enable responsiveness on mobile devices-->
                  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">

                  <!--Generated by Tsarev.ResumeBuilder --> 

                  <title>{Title} </title>

                  <meta name="author" context="{Author}" />
                  <meta name="description" context="{Description}" />

                  <style type="text/css">
                     {Resources.NormalizeCss}
                    {Resources.DefaultCss}
                  </style>
                  
                  

                </head>
            """;
    }
}
