name: ci

on:
  push:
    
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish (main only)
      if: github.event_name == 'push'
      shell: bash
      run: |
        dotnet tool install --global dotnet-releaser
        dotnet-releaser run --github-token "${{secrets.GITHUB_TOKEN}}" dotnet-releaser.toml


    - name: Build docker
      if: github.event_name == 'push'
      shell: bash
      run: |
        dotnet publish --os linux --arch x64 /t:PublishContainer
    
    - name: Login to docker registry
      if: github.event_name == 'push'
      shell: bash
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Push
      if: github.event_name == 'push'
      shell: bash
      run: |
        docker tag resumebuilder ghcr.io/leotsarev/resumebuilder
        docker push ghcr.io/leotsarev/resumebuilder
